#  ____            _       _____                                          _     
# |  _ \          (_)     / ____|                                        | |    
# | |_) | __ _ ___ _  ___| |     ___  _ __ ___  _ __ ___   __ _ _ __   __| |___ 
# |  _ < / _` / __| |/ __| |    / _ \| '_ ` _ \| '_ ` _ \ / _` | '_ \ / _` / __|
# | |_) | (_| \__ \ | (__| |___| (_) | | | | | | | | | | | (_| | | | | (_| \__ \
# |____/ \__,_|___/_|\___|\_____\___/|_| |_| |_|_| |_| |_|\__,_|_| |_|\__,_|___/                                     
#                                            By: LaxWasHere
LogReports: true
IRC:
    ReportsToIRC: true
    Channel: #MinecraftStaff
vote:
- '&6====================================================='
- '&a Vote for us at http://minecraftservers.org/server/54083'
- '&a And http://mcservers.org/detail/play.lazlecraft.net'
- '&6====================================================='
donate: 
- '&6&l============================================='
- '&aDonate to our awesome server and recive some awesome perks!'
- '&aVisit our shop at http://store.lazlecraft.net/'
- '&a If you want OP, simply donate $9999999999 monopoly money'
- '&6&l============================================='
website: 
- '&6&l============================================='
- '&aVisit our awesome website at http://LazleCraft.net'
- '&6&l============================================='